### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by meghagill** [Gardner-BinfLab/TIsigner#1]
Hi, 
I have been trying to incorporate the use of the optimiser into my own code, using the instructions as follows: 

from libs.functions import Optimiser
seq = 'ATGAAGAAAAGCTTATCCACCAGCGCTCGCCTCGAGGGAGGACTATCTATCTATCTATCTATCTTCGGCGGACGGACTACCATCGCATTACGGGGCTACGACGGACTCGATCTACTATCTATCTACTTCTAG'
my_opt = Optimiser(seq, host='ecoli', ncodons=None, utr=None, niter=None, threshold=None, plfold_args=None, rms_sites=None)
opt_seq = my_opt.simulated_anneal()

However, I have been getting this error from subprocess: 

C:\Users\megha\AppData\Local\Programs\Python\Python37-32\python.exe C:/Users/megha/PycharmProjects/iGEM_capsid/scrap.py
Traceback (most recent call last):
  File "C:/Users/megha/PycharmProjects/iGEM_capsid/scrap.py", line 4, in <module>
    opt_seq = my_opt.simulated_anneal()
  File "C:\Users\megha\PycharmProjects\iGEM_capsid\libs\functions.py", line 202, in simulated_anneal
    initial_cost = Optimiser.accessibility(self, seq)
  File "C:\Users\megha\PycharmProjects\iGEM_capsid\libs\functions.py", line 165, in accessibility
    encoding='utf-8')
  File "C:\Users\megha\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\megha\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Users\megha\AppData\Local\Programs\Python\Python37-32\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

Please could you let me know how I may solve this issue. I am new to programming and would appreciate that you could provide me with a detailed set of steps to solve this issue. 
Thank-you for your help. 

Kind regards, 

Megha

**Comment by bkb3** [comment]
HI Megha,

Sorry for delay. 
You can try opening file `functions.py` inside `libs` folder and edit the following line:
`run(all_args, stdout=PIPE, stderr=DEVNULL, input=input_seq, cwd=tmp, \
encoding='utf-8')`
to 
` run(all_args, stdout=PIPE, stderr=DEVNULL, input=input_seq, cwd=tmp, \
encoding='utf-8, shell=True')`
and see how it goes. 

Unfortunately, this is a Windows specific problem and TIsigner is tested on Linux based systems only (RHEL, Debian and Ubuntu) and currently the support is only on those systems. You can also try booting up Linux distribution in a VM and run the software again.
